### ISSUE TITLE
Cluster rendering or multi-threading?

### ISSUE THREAD

**Issue by nnhubbard** [rinigus/mapbox-gl-importer#12]
Does this project allow `openmaptiles` to use multi-threading or even cluster rendering to make `.mbtiles` generation faster than the standard `openmaptiles` project?

**Comment by rinigus** [comment]
I am not sure I follow what you ask specifically. It does allow importing using multiple processes (`make -jXXX`) , each process uses multithreaded import on a top of that. Since the planet is swiped in order of coordinates, there is locality aspect as well. When I timed, it looked to work faster than the import with a single process.

**Comment by nnhubbard** [comment]
Were you able to import the full planet into mbtiles using this method? If so, how long did that take and what hardware?

**Comment by rinigus** [comment]
Yes, I have been importing full planet and redistributing the tiles as a part of OSM Scout Server maps, multiple times now.

Good question regarding performance. I'll have to time it next time I will make the import (in a month or so). Last time, tuning was done as a part of #3 , but info over there is not full

**Comment by rinigus** [comment]
Closing as stale
